import os
import json


def rounded(minutes: int | float) -> float:
    """
    Converts minutes to hours and rounds the result to 3 decimal places.

    :param minutes: number of minutes
    :return: number of hours
    """
    hours = round(minutes / 60, 3)

    return hours


def to_numeric(path: str) -> None:
    """
    Converts text-based time values to numeric hours and saves them to JSON files in the specified path.

    :param path: the path of the mappers directory
    :return: a printed message indicating success
    """
    os.makedirs(path, exist_ok=True)

    duration_values_to_numeric_in_days = {"يوم واحد": 1,
                                          "يومين": 2,
                                          "ثلاثة أيام": 3,
                                          "أربعة أيام": 4,
                                          "خمسة أيام": 5,
                                          "ستة أيام": 6,
                                          "أسبوع": 7,
                                          "أسبوعين": 14,
                                          "ثلاثة أسابيع": 21,
                                          "شهر": 30}

    offer_response_time_values_to_numeric_in_hours = {"لم يحسب": None,
                                                      "أقل من دقيقة": rounded(0.5),
                                                      "دقيقة": rounded(1),
                                                      "دقيقتين": rounded(2),
                                                      "3 دقائق": rounded(3),
                                                      "4 دقائق": rounded(4),
                                                      "5 دقائق": rounded(5),
                                                      "6 دقائق": rounded(6),
                                                      "7 دقائق": rounded(7),
                                                      "8 دقائق": rounded(8),
                                                      "9 دقائق": rounded(9),
                                                      "10 دقائق": rounded(10),
                                                      "11 دقيقة": rounded(11),
                                                      "12 دقيقة": rounded(12),
                                                      "13 دقيقة": rounded(13),
                                                      "14 دقيقة": rounded(14),
                                                      "15 دقيقة": rounded(15),
                                                      "16 دقيقة": rounded(16),
                                                      "17 دقيقة": rounded(17),
                                                      "18 دقيقة": rounded(18),
                                                      "19 دقيقة": rounded(19),
                                                      "20 دقيقة": rounded(20),
                                                      "21 دقيقة": rounded(21),
                                                      "22 دقيقة": rounded(22),
                                                      "23 دقيقة": rounded(23),
                                                      "24 دقيقة": rounded(24),
                                                      "25 دقيقة": rounded(25),
                                                      "26 دقيقة": rounded(26),
                                                      "27 دقيقة": rounded(27),
                                                      "28 دقيقة": rounded(28),
                                                      "29 دقيقة": rounded(29),
                                                      "30 دقيقة": rounded(30),
                                                      "31 دقيقة": rounded(31),
                                                      "32 دقيقة": rounded(32),
                                                      "33 دقيقة": rounded(33),
                                                      "34 دقيقة": rounded(34),
                                                      "35 دقيقة": rounded(35),
                                                      "36 دقيقة": rounded(36),
                                                      "37 دقيقة": rounded(37),
                                                      "38 دقيقة": rounded(38),
                                                      "39 دقيقة": rounded(39),
                                                      "40 دقيقة": rounded(40),
                                                      "41 دقيقة": rounded(41),
                                                      "42 دقيقة": rounded(42),
                                                      "43 دقيقة": rounded(43),
                                                      "44 دقيقة": rounded(44),
                                                      "45 دقيقة": rounded(45),
                                                      "46 دقيقة": rounded(46),
                                                      "47 دقيقة": rounded(47),
                                                      "48 دقيقة": rounded(48),
                                                      "49 دقيقة": rounded(49),
                                                      "50 دقيقة": rounded(50),
                                                      "51 دقيقة": rounded(51),
                                                      "52 دقيقة": rounded(52),
                                                      "53 دقيقة": rounded(53),
                                                      "54 دقيقة": rounded(54),
                                                      "55 دقيقة": rounded(55),
                                                      "56 دقيقة": rounded(56),
                                                      "57 دقيقة": rounded(57),
                                                      "58 دقيقة": rounded(58),
                                                      "59 دقيقة": rounded(59),
                                                      "ساعة": rounded(60),
                                                      "ساعتين": rounded(120),
                                                      "3 ساعات": rounded(180),
                                                      "4 ساعات": rounded(240),
                                                      "5 ساعات": rounded(300),
                                                      "6 ساعات": rounded(360),
                                                      "7 ساعات": rounded(420),
                                                      "8 ساعات": rounded(480),
                                                      "9 ساعات": rounded(540),
                                                      "10 ساعات": rounded(600),
                                                      "11 ساعة": rounded(660),
                                                      "12 ساعة": rounded(720),
                                                      "13 ساعة": rounded(780),
                                                      "14 ساعة": rounded(840),
                                                      "15 ساعة": rounded(900),
                                                      "16 ساعة": rounded(960),
                                                      "17 ساعة": rounded(1020),
                                                      "18 ساعة": rounded(1080),
                                                      "19 ساعة": rounded(1140),
                                                      "20 ساعة": rounded(1200),
                                                      "21 ساعة": rounded(1260),
                                                      "22 ساعة": rounded(1320),
                                                      "23 ساعة": rounded(1380),
                                                      "يوم": rounded(1440),
                                                      "يومين": rounded(2880),
                                                      "3 أيام": rounded(4320),
                                                      "4 أيام": rounded(5760),
                                                      "5 أيام": rounded(7200),
                                                      "6 أيام": rounded(8640),
                                                      "7 أيام": rounded(10080),
                                                      "8 أيام": rounded(11520),
                                                      "9 أيام": rounded(12960),
                                                      "10 أيام": rounded(14400),
                                                      "11 يوم": rounded(15840),
                                                      "12 يوم": rounded(17280),
                                                      "13 يوم": rounded(18720),
                                                      "14 يوم": rounded(20160),
                                                      "16 يوم": rounded(23040),
                                                      "18 يوم": rounded(25920),
                                                      "20 يوم": rounded(28800),
                                                      "23 يوم": rounded(33120),
                                                      "25 يوم": rounded(36000),
                                                      "26 يوم": rounded(37440)}

    owner_response_time_values_to_numeric_in_hours = {"لم يحسب": None,
                                                      "أقل من دقيقة": rounded(0.5),
                                                      "دقيقة": rounded(1),
                                                      "دقيقتين": rounded(2),
                                                      "3 دقائق": rounded(3),
                                                      "4 دقائق": rounded(4),
                                                      "5 دقائق": rounded(5),
                                                      "6 دقائق": rounded(6),
                                                      "7 دقائق": rounded(7),
                                                      "8 دقائق": rounded(8),
                                                      "9 دقائق": rounded(9),
                                                      "10 دقائق": rounded(10),
                                                      "11 دقيقة": rounded(11),
                                                      "12 دقيقة": rounded(12),
                                                      "13 دقيقة": rounded(13),
                                                      "14 دقيقة": rounded(14),
                                                      "15 دقيقة": rounded(15),
                                                      "16 دقيقة": rounded(16),
                                                      "17 دقيقة": rounded(17),
                                                      "18 دقيقة": rounded(18),
                                                      "19 دقيقة": rounded(19),
                                                      "20 دقيقة": rounded(20),
                                                      "21 دقيقة": rounded(21),
                                                      "22 دقيقة": rounded(22),
                                                      "23 دقيقة": rounded(23),
                                                      "24 دقيقة": rounded(24),
                                                      "25 دقيقة": rounded(25),
                                                      "26 دقيقة": rounded(26),
                                                      "27 دقيقة": rounded(27),
                                                      "28 دقيقة": rounded(28),
                                                      "29 دقيقة": rounded(29),
                                                      "30 دقيقة": rounded(30),
                                                      "31 دقيقة": rounded(31),
                                                      "32 دقيقة": rounded(32),
                                                      "33 دقيقة": rounded(33),
                                                      "34 دقيقة": rounded(34),
                                                      "35 دقيقة": rounded(35),
                                                      "36 دقيقة": rounded(36),
                                                      "37 دقيقة": rounded(37),
                                                      "38 دقيقة": rounded(38),
                                                      "39 دقيقة": rounded(39),
                                                      "40 دقيقة": rounded(40),
                                                      "41 دقيقة": rounded(41),
                                                      "42 دقيقة": rounded(42),
                                                      "43 دقيقة": rounded(43),
                                                      "44 دقيقة": rounded(44),
                                                      "45 دقيقة": rounded(45),
                                                      "46 دقيقة": rounded(46),
                                                      "47 دقيقة": rounded(47),
                                                      "48 دقيقة": rounded(48),
                                                      "49 دقيقة": rounded(49),
                                                      "50 دقيقة": rounded(50),
                                                      "51 دقيقة": rounded(51),
                                                      "52 دقيقة": rounded(52),
                                                      "53 دقيقة": rounded(53),
                                                      "54 دقيقة": rounded(54),
                                                      "55 دقيقة": rounded(55),
                                                      "56 دقيقة": rounded(56),
                                                      "57 دقيقة": rounded(57),
                                                      "58 دقيقة": rounded(58),
                                                      "59 دقيقة": rounded(59),
                                                      "ساعة": rounded(60),
                                                      "ساعتين": rounded(120),
                                                      "3 ساعات": rounded(180),
                                                      "4 ساعات": rounded(240),
                                                      "5 ساعات": rounded(300),
                                                      "6 ساعات": rounded(360),
                                                      "7 ساعات": rounded(420),
                                                      "8 ساعات": rounded(480),
                                                      "9 ساعات": rounded(540),
                                                      "10 ساعات": rounded(600),
                                                      "11 ساعة": rounded(660),
                                                      "12 ساعة": rounded(720),
                                                      "13 ساعة": rounded(780),
                                                      "14 ساعة": rounded(840),
                                                      "15 ساعة": rounded(900),
                                                      "16 ساعة": rounded(960),
                                                      "17 ساعة": rounded(1020),
                                                      "18 ساعة": rounded(1080),
                                                      "19 ساعة": rounded(1140),
                                                      "20 ساعة": rounded(1200),
                                                      "21 ساعة": rounded(1260),
                                                      "22 ساعة": rounded(1320),
                                                      "23 ساعة": rounded(1380),
                                                      "يوم": rounded(1440),
                                                      "يومين": rounded(2880),
                                                      "3 أيام": rounded(4320),
                                                      "4 أيام": rounded(5760),
                                                      "5 أيام": rounded(7200),
                                                      "6 أيام": rounded(8640),
                                                      "7 أيام": rounded(10080),
                                                      "8 أيام": rounded(11520),
                                                      "9 أيام": rounded(12960),
                                                      "10 أيام": rounded(14400),
                                                      "11 يوم": rounded(15840),
                                                      "12 يوم": rounded(17280),
                                                      "13 يوم": rounded(18720),
                                                      "14 يوم": rounded(20160),
                                                      "17 يوم": rounded(24480),
                                                      "20 يوم": rounded(28800),
                                                      "22 يوم": rounded(31680),
                                                      "26 يوم": rounded(37440)}

    duration_values_file = os.path.join(path, "duration.json")
    offer_response_time_file = os.path.join(path, "offer_response_time.json")
    owner_response_time_file = os.path.join(path, "owner_response_time.json")

    values = [duration_values_to_numeric_in_days,
              offer_response_time_values_to_numeric_in_hours,
              owner_response_time_values_to_numeric_in_hours]

    files = [duration_values_file,
             offer_response_time_file,
             owner_response_time_file]

    for numeric_value, numeric_file in zip(values, files):
        with open(numeric_file, "w", encoding="utf-8") as file:
            json.dump(numeric_value, file, ensure_ascii=False)

    print(f"Numeric mapper files: {os.listdir(path)}, and saved in '{path}'.")
